force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Issuer__c.field-meta.xml
<CustomField>
    <fullName>Issuer__c</fullName>
    <label>Issuer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Degree_Type__c.field-meta.xml
<CustomField>
    <fullName>Degree_Type__c</fullName>
    <label>Degree Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Associate Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Doctoral Degree</fullName>
            </value>
            <value>
                <fullName>Master&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>This object represents a profile. It contains attributes for the desired role and the headline to be displayed on the resume.</description>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Applicant_User__c.field-meta.xml
<CustomField>
    <fullName>Applicant_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>BYR Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <description>This object represents a resume associated with a profile. For example, a user could create a profile &quot;Technical Program Manager&quot; to apply for TPM roles. They could then create a Resume record of a profile when applying to jobs.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume__c/fields/Highlights__c.field-meta.xml
<CustomField>
    <fullName>Highlights__c</fullName>
    <label>Highlights</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Resumes</relationshipLabel>
    <relationshipName>Resumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <inlineHelpText>This is the summary that you would like to display on your profile.</inlineHelpText>
    <label>Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Resume_Certification__c/Resume_Certification__c.object-meta.xml
<CustomObject>
    <label>Resume Certification</label>
    <nameField>
        <displayFormat>RCID-{0000}</displayFormat>
        <label>Resume Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Certification__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Certifications</relationshipLabel>
    <relationshipName>Linked_Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Education__c/Resume_Education__c.object-meta.xml
<CustomObject>
    <label>Resume Education</label>
    <nameField>
        <displayFormat>RED-ID-{0000}</displayFormat>
        <label>Resume Education ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Education__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <referenceTo>Education__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Education__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Education</relationshipLabel>
    <relationshipName>Linked_Education</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Experience__c/Resume_Experience__c.object-meta.xml
<CustomObject>
    <label>Resume Experience</label>
    <nameField>
        <displayFormat>REID-{0000}</displayFormat>
        <label>Resume Experience ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Experience</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Work Experience</relationshipLabel>
    <relationshipName>Linked_Work_Experience</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Experience__c/fields/Work_Experience__c.field-meta.xml
<CustomField>
    <fullName>Work_Experience__c</fullName>
    <label>Work Experience</label>
    <referenceTo>Work_Experience__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Skill__c/Resume_Skill__c.object-meta.xml
<CustomObject>
    <label>Resume Skill</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>Resume Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Skill__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Skills</relationshipLabel>
    <relationshipName>Linked_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experience</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Enter the Location as City, State</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ResumeDeepClone.cls
public with sharing class ResumeDeepClone {
    public ResumeDeepClone() {}

    public class Request {
        @InvocableVariable(required=true label='Resume IDs')
        public List<Id> resumeIds;
    }

    public class Result {
        @InvocableVariable(label='Old Resume ID')
        public Id oldResumeId;
        
        @InvocableVariable(label='New Resume ID')
        public Id newResumeId;
        
        @InvocableVariable(label='Error Message')
        public String errorMessage;
    }
    
    @InvocableMethod(label='Deep Clone Resumes' description='Deep clone Resumes and all related records')
    public static List<Result> deepCloneResumes(List<Request> requests) {
        // Gather all IDs across requests (supports both single and bulk)
        Set<Id> resumeIds = new Set<Id>();
        for (Request req : requests) {
            if (req.resumeIds != null) {
                resumeIds.addAll(req.resumeIds);
            }
        }
        if (resumeIds.isEmpty()) {
            return new List<Result>();
        }

        // Query the resume and its related records
        List<Resume__c> resumes = [
            //Get top level resume fields from the Resume__c object
            SELECT Id, Name, Summary__c, Highlights__c, Cover_Letter__c,

                //Get related profile fields from the Profile__c object
                Profile__c, Profile__r.id, Profile__r.name,

                //Get fields from the User object related to the Profile object
                profile__r.applicant_user__c, profile__r.applicant_user__r.name, 
                profile__r.applicant_user__r.email, profile__r.applicant_user__r.mobilephone, 
                profile__r.applicant_user__r.city, profile__r.applicant_user__r.state,

                //Get related records from the junction object for Work Experience
                //Relationship =Linked_Work_Experience__r
                //Object = Resume_Experience__c
                (SELECT ID, Name, Resume__c, Work_Experience__c, responsibilities__c, 
                        Work_Experience__r.id, Work_Experience__r.name, Work_Experience__r.company__c, 
                        Work_Experience__r.role__c, Work_Experience__r.location__c,
                        Work_Experience__r.from_date__c, Work_Experience__r.to_date__c 
                FROM Linked_Work_Experience__r), 

                //Get related records from the junction object for Certiifications
                //Relationship = Linked_Certifications__r
                //Object = Resume_Certification__c
                (SELECT ID, Name, Resume__c, Certification__c, Certification__r.id, Certification__r.name, 
                        Certification__r.issuer__c, Certification__r.date_achieved__c 
                FROM Linked_Certifications__r), 

                //Get related records from the junction object for Education
                //Relationship = Linked_Education__r
                //Object = Resume_Education__c
                (SELECT ID, Name, Resume__c, Education__c, Education__r.id, Education__r.name, 
                        Education__r.institution_name__c, Education__r.degree_type__c, 
                        Education__r.field_of_study__c, Education__r.date_achieved__c 
                FROM Linked_Education__r), 

                //Get related records from the junction object for Skills
                //Relationship = Linked_Skills__r
                //Object = Resume_Skill__c
                (SELECT ID, Name, Resume__c, Skill__c, Skill__r.id, Skill__r.name 
                FROM Linked_Skills__r)

            //back to the top level object Resume__c
            FROM Resume__c 
            WHERE Id IN :resumeIds
        ];
        
        if (resumes.isEmpty()) {
            return new List<Result>();
        }

        // Clone resumes and related records
        List<Resume__c> clonedResumes = new List<Resume__c>();
        Map<Id, Resume__c> oldToNewResumeMap = new Map<Id, Resume__c>();
        
        for (Resume__c resume : resumes) {
            Resume__c cloned = resume.clone(false, true, false, false);
            cloned.Name = resume.Name + ' (Copy)';
            clonedResumes.add(cloned);
            oldToNewResumeMap.put(resume.Id, cloned);
        }
        
        insert clonedResumes;
        
        // Clone junction records
        List<Resume_Experience__c> clonedExperiences = new List<Resume_Experience__c>();
        List<Resume_Certification__c> clonedCertifications = new List<Resume_Certification__c>();
        List<Resume_Education__c> clonedEducation = new List<Resume_Education__c>();
        List<Resume_Skill__c> clonedSkills = new List<Resume_Skill__c>();
        
        for (Resume__c resume : resumes) {
            Resume__c newResume = oldToNewResumeMap.get(resume.Id);
            
            for (Resume_Experience__c exp : resume.Linked_Work_Experience__r) {
                Resume_Experience__c clonedExp = exp.clone(false, true, false, false);
                clonedExp.Resume__c = newResume.Id;
                clonedExperiences.add(clonedExp);
            }
            
            for (Resume_Certification__c cert : resume.Linked_Certifications__r) {
                Resume_Certification__c clonedCert = cert.clone(false, true, false, false);
                clonedCert.Resume__c = newResume.Id;
                clonedCertifications.add(clonedCert);
            }
            
            for (Resume_Education__c edu : resume.Linked_Education__r) {
                Resume_Education__c clonedEdu = edu.clone(false, true, false, false);
                clonedEdu.Resume__c = newResume.Id;
                clonedEducation.add(clonedEdu);
            }
            
            for (Resume_Skill__c skill : resume.Linked_Skills__r) {
                Resume_Skill__c clonedSkill = skill.clone(false, true, false, false);
                clonedSkill.Resume__c = newResume.Id;
                clonedSkills.add(clonedSkill);
            }
        }
        
        if (!clonedExperiences.isEmpty()) insert clonedExperiences;
        if (!clonedCertifications.isEmpty()) insert clonedCertifications;
        if (!clonedEducation.isEmpty()) insert clonedEducation;
        if (!clonedSkills.isEmpty()) insert clonedSkills;
        
        // Build results
        List<Result> results = new List<Result>();
        for (Id oldId : oldToNewResumeMap.keySet()) {
            Result r = new Result();
            r.oldResumeId = oldId;
            r.newResumeId = oldToNewResumeMap.get(oldId).Id;
            results.add(r);
        }
        
        return results;
    }
}