force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Degree_Type__c.field-meta.xml
<CustomField>
    <fullName>Degree_Type__c</fullName>
    <label>Degree Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Associate Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Doctoral Degree</fullName>
            </value>
            <value>
                <fullName>Master&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <description>This object represents a profile. It contains attributes for the desired role and the headline to be displayed on the resume.</description>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <description>This object represents a resume associated with a profile. For example, a user could create a profile &quot;Technical Program Manager&quot; to apply for TPM roles. They could then create a Resume record of a profile when applying to jobs.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Resumes</relationshipLabel>
    <relationshipName>Resumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Certification__c/Resume_Certification__c.object-meta.xml
<CustomObject>
    <label>Resume Certification</label>
    <nameField>
        <displayFormat>RCID-{0000}</displayFormat>
        <label>Resume Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Certification__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Certifications</relationshipLabel>
    <relationshipName>Linked_Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Education__c/Resume_Education__c.object-meta.xml
<CustomObject>
    <label>Resume Education</label>
    <nameField>
        <displayFormat>RED-ID-{0000}</displayFormat>
        <label>Resume Education ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Education__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <referenceTo>Education__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Education__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Education</relationshipLabel>
    <relationshipName>Linked_Education</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Experience__c/Resume_Experience__c.object-meta.xml
<CustomObject>
    <label>Resume Experience</label>
    <nameField>
        <displayFormat>REID-{0000}</displayFormat>
        <label>Resume Experience ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Experience</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Work Experience</relationshipLabel>
    <relationshipName>Linked_Work_Experience</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Experience__c/fields/Work_Experience__c.field-meta.xml
<CustomField>
    <fullName>Work_Experience__c</fullName>
    <label>Work Experience</label>
    <referenceTo>Work_Experience__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Skill__c/Resume_Skill__c.object-meta.xml
<CustomObject>
    <label>Resume Skill</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>Resume Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Skill__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Linked Skills</relationshipLabel>
    <relationshipName>Linked_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Linked Resumes</relationshipLabel>
    <relationshipName>Linked_Resumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experience</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Enter the Location as City, State</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BYROS_ResumeServiceTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class BYROS_ResumeServiceTest {

    @TestSetup
    static void createTestData(){

        // Create test data
        System.debug('Entering ResumeServiceTest.createTestData, inserting profiles');

        //Insert Profiles
        insert new Profile__c(Name='Profile A');
        insert new Profile__c(Name='Profile B');

        // Retrieve profiles
        List<Profile__c> profiles = [SELECT Id, Name FROM Profile__c];

        System.debug('Inside ResumeServiceTest.createTestData, inserted profiles ' + profiles);

        System.debug('Inside ResumeServiceTest.createTestData, inserting resumes');
        
        // Insert resumes for profiles
        insert new Resume__c(Name='Resume A1', profile__c = profiles[0].Id);
        insert new Resume__c(Name='Resume A2', profile__c = profiles[0].Id);
        insert new Resume__c(Name='Resume B1', profile__c = profiles[1].Id);
        
        List<Resume__c> resumes = [SELECT Id, Name, profile__c FROM Resume__c];

        //insert Education, Work Experience, Skills, and Certifications
        //insert junction objects
        //update resume and junction relationships
        System.debug('Inside ResumeServiceTest.createTestData, inserting education, work experience, skills, and certifications');

        insert new Education__c(Name='Education A1', Institution_Name__c='Institution A1', Degree_Type__c='Degree Type A1', Field_of_Study__c='Field of Study A1', Date_Achieved__c=Date.today());
        insert new Education__c(Name='Education A2', Institution_Name__c='Institution A2', Degree_Type__c='Degree Type A2', Field_of_Study__c='Field of Study A2', Date_Achieved__c=Date.today());
        List<Education__c> educationRecords = [SELECT Id, Name, Institution_Name__c, Degree_Type__c, Field_of_Study__c, Date_Achieved__c FROM Education__c];
        System.debug('Inside ResumeServiceTest.createTestData, inserted education records ' + educationRecords);

        insert new Work_Experience__c(Name='Work Experience A1', Company__c='Company A1', Role__c='Role A1', Location__c='Location A1', From_Date__c=Date.today(), To_Date__c=Date.today());
        List<Work_Experience__c> workExperienceRecords = [SELECT Id, Name, Company__c, Role__c, Location__c, From_Date__c, To_Date__c FROM Work_Experience__c];
        System.debug('Inside ResumeServiceTest.createTestData, inserted work experience records ' + workExperienceRecords);

        insert new Skill__c(Name='Skill A1');
        List<Skill__c> skillRecords = [SELECT Id, Name FROM Skill__c];
        System.debug('Inside ResumeServiceTest.createTestData, inserted skill records ' + skillRecords);

        insert new Certification__c(Name='Certification A1');
        List<Certification__c> certificationRecords = [SELECT Id, Name FROM Certification__c];
        System.debug('Inside ResumeServiceTest.createTestData, inserted certification records ' + certificationRecords);

        insert new Resume_Skill__c(Resume__c = resumes[0].Id, Skill__c = skillRecords[0].Id);
        insert new Resume_Experience__c(Resume__c = resumes[0].Id, Work_Experience__c = workExperienceRecords[0].Id);
        insert new Resume_Certification__c(Resume__c = resumes[0].Id, Certification__c = certificationRecords[0].Id);
        insert new Resume_Education__c(Resume__c = resumes[0].Id, Education__c = educationRecords[0].Id);
        System.debug('Inside ResumeServiceTest.createTestData, inserted junction objects');

        System.debug('Exiting ResumeServiceTest.createTestData ' );

    }

    @IsTest 
    static void testGetProfiles() {
        //Test coverage for getProfiles
        Test.startTest();
        List<ResumeService.ProfileList> profileList = ResumeService.getProfiles();
        System.debug('Inside ResumeServiceTest.testGetProfiles, Testing coverage for getProfiles ' + profileList);
        Test.stopTest();

        System.assertEquals(2, profileList.size(), 'Expected 2 profiles');
    }

    @IsTest 
    static void testGetResumesForProfile() {
        //Test coverage for getResumes(profileId)
        Test.startTest();
        List<BYROS_ResumeService.ProfileList> profileList = BYROS_ResumeService.getProfiles();
        List<BYROS_ResumeService.ResumeList> resumeList = BYROS_ResumeService.getResumes(profileList[0].value);
        System.debug('Inside ResumeServiceTest.testGetResumesForProfile, Testing coverage for getResumes(profileId) ' + resumeList);
        Test.stopTest();

        System.assertEquals(2, resumeList.size(), 'Expected 2 resumes');
    }

    @IsTest 
    static void testGetAllResumes() {
        //Test coverage for getAllResumes()
        Test.startTest();
        List<BYROS_ResumeService.ResumeList> allResumes = BYROS_ResumeService.getAllResumes();
        System.debug('Inside ResumeServiceTest.testGetAllResumes, Testing coverage for getAllResumes() ' + allResumes);
        Test.stopTest();

        System.assertEquals(3, allResumes.size(), 'Expected 3 resumes');     
    }

    @IsTest 
    static void testGetResumeDetails() {    
        //Test coverage for getResumeDetails(resumeId)
        Test.startTest();
        List<BYROS_ResumeService.ResumeList> allResumes = BYROS_ResumeService.getAllResumes();
        BYROS_ResumeService.ResumeDetails resumeDetails = BYROS_ResumeService.getResumeDetails(allResumes[0].value);
        System.debug('Inside ResumeServiceTest.testGetResumeDetails, Testing coverage for getResumeDetails(resumeId) ' + resumeDetails);
        Test.stopTest();
        System.assertNotEquals(null, resumeDetails, 'resumeDetails should not be null');
        
    }
}